# Generated by Django 2.1.5 on 2019-01-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass', models.CharField(max_length=20, verbose_name='クラスタリングのタイトル')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=140, verbose_name='URL')),
                ('site_name', models.CharField(max_length=20, verbose_name='URLの説明')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='日付')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='url.SubClass', verbose_name='タイトルの名前')),
            ],
        ),
    ]
