# Generated by Django 2.1.5 on 2019-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclass',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='日付'),
        ),
    ]
