# Generated by Django 2.1.5 on 2019-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, verbose_name='タイトル')),
                ('amazon_url', models.URLField(verbose_name='URL')),
            ],
        ),
    ]
