# Generated by Django 2.1.5 on 2019-02-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.CharField(max_length=40, verbose_name='タイトル'),
        ),
    ]
