# Generated by Django 2.1.5 on 2019-02-13 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190213_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Imageurl'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='amazon_url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
    ]
